<a href="https://colab.research.google.com/github/ansuman1981/python-project-for-data-science-/blob/main/gamestop_vs_tesla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tesla vs GameStop stock**

**section 1**

**Extract Tesla stock data**

in this first section we are using the first workflow which is extract data.

**1. Extract data**
in extract data we collect the data:


*   stock prices
*   revenue/profit data

we will use:


*   APIs(yfinance)
*   webscracping
*   pandas

In [1]:
# install yfinance
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.4.22)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [2]:
# import libraries
import yfinance as yf
import pandas as pd

In [3]:
# Create tesla stock object
tesla = yf.Ticker("TSLA")

In [4]:
# Extract Historical Stock Data
tesla_data = tesla.history(period="max") # Get all available Tesla stock history

**Reset Index**
what the reson behid we are reseting the index:

intitally the date is stored as the index.we convert it to a nominal column for easier analysis and plotting.

In [5]:
# Reset index
tesla_data.reset_index(inplace=True)

In [6]:
# view the data
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

## Tesla stock data was successfully extracted using the yfinance library. The dataset includes historical stock prices and trading volume information.
information we get from the data:

*  Date
*  Open
*  High
*  Low
*  Close
*  Volume
*  Dividends
*  Stock Splits

In [14]:
tesla_data.tail() # view the last row
# it shows latests stock data and newest date

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
3985,2026-05-04 00:00:00-04:00,390.230011,394.640015,384.799988,392.510010,48765100,0.0,0.0
3986,2026-05-05 00:00:00-04:00,395.190002,402.119995,389.000000,389.369995,47780600,0.0,0.0
3987,2026-05-06 00:00:00-04:00,386.250000,401.679993,384.019989,398.730011,53465400,0.0,0.0
3988,2026-05-07 00:00:00-04:00,407.480011,415.829987,402.119995,411.790009,64294200,0.0,0.0
3989,2026-05-08 00:00:00-04:00,416.480011,431.200012,416.390015,428.350006,64880800,0.0,0.0

In [15]:
# check dataset shape
tesla_data.shape # row and column

(3990, 8)

In [16]:
# see clomm name
""" check data informations """
tesla_data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits'],
      dtype='object')

In [17]:
# basic data info
tesla_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3990 entries, 0 to 3989
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3990 non-null   datetime64[ns, America/New_York]
 1   Open          3990 non-null   float64
 2   High          3990 non-null   float64
 3   Low           3990 non-null   float64
 4   Close         3990 non-null   float64
 5   Volume        3990 non-null   int64
 6   Dividends     3990 non-null   float64
 7   Stock Splits  3990 non-null   float64
dtypes: datetime64[ns, America/New_York](1), float64(6), int64(1)
memory usage: 249.5 KB

In [18]:
# basic statastics
tesla_data.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,3990.000000,3990.000000,3990.000000,3990.000000,3.990000e+03,3990.0,3990.000000
mean,105.864496,108.139265,103.452418,105.843013,9.599315e+07,0.0,0.002005
std,131.782105,134.543903,128.801254,131.706580,7.505338e+07,0.0,0.092301
min,1.076000,1.108667,0.998667,1.053333,1.777500e+06,0.0,0.000000
25%,12.951500,13.227667,12.705167,12.969001,5.165588e+07,0.0,0.000000
50%,20.322333,20.614334,19.939667,20.367333,8.191575e+07,0.0,0.000000
75%,217.325001,222.000000,212.162495,217.146671,1.199726e+08,0.0,0.000000
max,489.880005,498.829987,485.329987,489.880005,9.140820e+08,0.0,5.000000

# EDA
**Exploratory Data Analysis (EDA)**

**why EDA matters**
* what data is exists
* whether data is clean
* what trend may appear

The Tesla stock dataset was inspected using exploratory data analysis techniques such as viewing rows, checking column types, and analyzing statistical summaries.

# **Extract Revenue data through Web Scraping**
now we move to the second most major part of the project:

**Extracting company revenue/profit data from webpages.**

## What is Revenue data?
the money earned by the business company  from its business operations.

## Why compare Revenue with stock data?
Because sometimes:    
* stoc price rises but comapany profit and loss and revenus do not.

**This helps Analysts understand:**
* hype
* overvaluation
* investor behavior

# Website

#   ↓

# Download HTML

#   ↓

# Parse HTML

#   ↓

# Find revenue table

#   ↓
   
# Convert into DataFrame

In [7]:
# import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

In [8]:
# download webpage
url = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"

## Important
we are using **Macrotrends** use commanly used to get real bases data or info about revenue and other comapnies info and the main reasons are:
* esier to scrape
* conatains revenue tables
* less blocking then yahoo

In [9]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Referer": "https://www.google.com/",
    "DNT": "1",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

In [10]:
# request Webpage
html_data =  requests.get(url,headers=headers).text

## What happen here?
**visit webpage --- download HTML source code**

In [11]:
soup = BeautifulSoup(html_data, "html.parser")